# Generated by Django 2.1.7 on 2019-04-01 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='serverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('resultPath', models.CharField(max_length=32)),
                ('serverId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='linuxInfoMoni.serverInfo')),
            ],
        ),
    ]
