# Generated by Django 2.1.7 on 2019-04-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='serverName',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
    ]
