# Generated by Django 2.1.7 on 2019-04-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0002_serverinfo_servername'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='comments',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
    ]
