# Generated by Django 2.1.7 on 2019-04-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0003_userinfo_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='comments',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
