# Generated by Django 2.1.7 on 2019-04-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0004_auto_20190401_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='serverId',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='comments',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='pwd',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='resultPath',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='uname',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
