# Generated by Django 2.1.7 on 2019-04-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0006_auto_20190402_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfo',
            name='comments',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='isTraced',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
