# Generated by Django 2.1.7 on 2019-04-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0007_auto_20190402_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='trace_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('usr_cpu', models.CharField(max_length=12)),
                ('sys_cpu', models.CharField(max_length=12)),
                ('total_cpu', models.CharField(max_length=12)),
                ('recvList', models.CharField(max_length=12)),
                ('sendList', models.CharField(max_length=12)),
                ('total_dk', models.CharField(max_length=12)),
                ('mem_used', models.CharField(max_length=12)),
                ('mem_free', models.CharField(max_length=12)),
                ('mem_cach', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='trace_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_name', models.CharField(max_length=32)),
                ('server_id', models.ForeignKey(on_delete='PROTECT', to='linuxInfoMoni.serverInfo')),
            ],
        ),
        migrations.AddField(
            model_name='trace_detail',
            name='trace_id',
            field=models.ForeignKey(on_delete='PROTECT', to='linuxInfoMoni.trace_info'),
        ),
    ]
