# Generated by Django 2.1.7 on 2019-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0008_auto_20190403_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trace_detail',
            old_name='mem_cach',
            new_name='mem_cache',
        ),
        migrations.AlterField(
            model_name='trace_detail',
            name='trace_id',
            field=models.ForeignKey(on_delete='CASCADE', to='linuxInfoMoni.trace_info'),
        ),
    ]
