# Generated by Django 2.1.7 on 2019-04-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0010_trace_detail_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trace_detail',
            name='data',
        ),
        migrations.AddField(
            model_name='trace_info',
            name='data',
            field=models.CharField(default='test', max_length=12),
            preserve_default=False,
        ),
    ]
