# Generated by Django 2.1.7 on 2019-04-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linuxInfoMoni', '0011_auto_20190403_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace_detail',
            name='trace_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linuxInfoMoni.trace_info'),
        ),
    ]
